version: 2

builds:
  - binary: gh-activity
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false

checksum:
  name_template: checksums.txt

release:
  github:
    owner: yskttm
    name: gh-activity
